### PR TITLE
Support parsing and displaying balance verification field in Posting.

### LINKED ISSUE #4: Balance assertion support
Would it be reasonable to add [balance verifications](https://www.ledger-cli.org/3.0/doc/ledger3.html#Balance-verification) to `Posting`s and the parser? A downside would be that this would likely require a major version bump due to the new (optional) field in `Posting`.

This is probably something that I can attempt to implement myself with a pull request if it seems like a reasonable feature to add.

### PR DESCRIPTION
**Pull request by huin**
Fixes #4.

### CODE REVIEW

**Comment by huin** [comment]
Should this be merged into a devel/feature branch?

**Comment by marek-g** [comment]
Thanks! That was quick :) I hope to find some time in a week or two to release it with a new version.

**Comment by huin** [comment]
No problem - your code was straightforward to understand and change :)

**Comment by marek-g** [comment]
Nice to hear it :)

**Pull request merged**
